version: "3.3"
services:

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - 5000:5000
    environment:
      MYSQL_HOSTNAME: database
      MYSQL_USERNAME: icu_username
      MYSQL_PASSWORD: icu_password
      MYSQL_DATABASE: icu_database
    depends_on:
      - database

  simulator:
    build:
      context: .
      dockerfile: Dockerfile.simulator
    environment:
      MYSQL_HOSTNAME: database
      MYSQL_USERNAME: icu_username
      MYSQL_PASSWORD: icu_password
      MYSQL_DATABASE: icu_database
    depends_on:
      - database

  database:
    build:
      context: .
      dockerfile: Dockerfile.database
    environment:
      MYSQL_USER: icu_username
      MYSQL_PASSWORD: icu_password
      MYSQL_ROOT_PASSWORD: icu_rootpass
      MYSQL_DATABASE: icu_database

  # Interface for our own MySQL database
  database-manager:
    image: phpmyadmin/phpmyadmin:4.8.5
    ports:
      - 8080:80
    environment:
      PMA_HOST: database
      MYSQL_USER: icu_username
      MYSQL_PASSWORD: icu_password
